# Generated by Django 5.1.5 on 2025-01-28 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_user_is_verified'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NormalUserProfile',
            new_name='UserProfile',
        ),
    ]
