# Generated by Django 5.1.5 on 2025-01-29 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_normaluserprofile_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='increment_version',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
