# Generated by Django 5.1.5 on 2025-01-30 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_increment_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='selleruserprofile',
            name='national_code',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='selleruserprofile',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='selleruserprofile',
            name='phone_number',
            field=models.CharField(max_length=12, null=True, unique=True),
        ),
    ]
