# Generated by Django 5.1.5 on 2025-01-30 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_selleruserprofile_national_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='selleruserprofile',
            name='status',
        ),
    ]
