# Generated by Django 5.1.5 on 2025-01-30 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_selleruserprofile_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='selleruserprofile',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
