# Generated by Django 5.1.5 on 2025-01-30 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_selleruserprofile_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selleruserprofile',
            name='first_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='selleruserprofile',
            name='last_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
