# Generated by Django 5.1.5 on 2025-03-09 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_selleruserprofile_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='cell_phone',
            field=models.CharField(max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='name',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
